export const DEMO_PLACES = [
  { id: 'p1', tripId: '1', dayId: 'd1', name: 'Narita Airport', time: '07:00', category: 'Transport', mapsUrl: 'https://maps.google.com/?q=Narita+Airport+Japan', lat: '35.7719', lng: '140.3929', notes: 'Arrive Terminal 1. Buy IC card here.' },
  { id: 'p2', tripId: '1', dayId: 'd1', name: 'Shinjuku Station', time: '09:30', category: 'Transport', mapsUrl: 'https://maps.google.com/?q=Shinjuku+Station+Tokyo', lat: '35.6896', lng: '139.7006', notes: 'Take Narita Express (N\'EX)' },
  { id: 'p3', tripId: '1', dayId: 'd1', name: 'Ace Hotel Tokyo', time: '15:00', category: 'Stay', mapsUrl: 'https://maps.google.com/?q=Ace+Hotel+Tokyo', lat: '35.6648', lng: '139.7127', notes: 'Check-in from 15:00' },
  { id: 'p4', tripId: '1', dayId: 'd1', name: 'Omoide Yokocho', time: '19:30', category: 'Food', mapsUrl: 'https://maps.google.com/?q=Omoide+Yokocho+Shinjuku', lat: '35.6930', lng: '139.6993', notes: 'Memory Lane — tiny ramen and yakitori stalls' },
  { id: 'p5', tripId: '1', dayId: 'd2', name: 'Meiji Shrine', time: '09:00', category: 'Sights', mapsUrl: 'https://maps.google.com/?q=Meiji+Shrine+Tokyo', lat: '35.6764', lng: '139.6993', notes: 'Arrive early to beat crowds' },
  { id: 'p6', tripId: '1', dayId: 'd2', name: 'Takeshita Street', time: '10:30', category: 'Shopping', mapsUrl: 'https://maps.google.com/?q=Takeshita+Street+Harajuku', lat: '35.6702', lng: '139.7026', notes: 'Harajuku fashion street' },
  { id: 'p7', tripId: '1', dayId: 'd2', name: 'Afuri Ramen', time: '13:00', category: 'Food', mapsUrl: 'https://maps.google.com/?q=Afuri+Ramen+Harajuku', lat: '35.6694', lng: '139.7039', notes: 'Yuzu shio ramen — get there early, queues form' },
  { id: 'p8', tripId: '1', dayId: 'd2', name: 'Shibuya Crossing', time: '15:30', category: 'Sights', mapsUrl: 'https://maps.google.com/?q=Shibuya+Scramble+Crossing', lat: '35.6595', lng: '139.7004', notes: 'Most famous crossing in the world' },
  { id: 'p9', tripId: '1', dayId: 'd2', name: 'Shibuya Sky', time: '20:00', category: 'Sights', mapsUrl: 'https://maps.google.com/?q=Shibuya+Sky+Observatory', lat: '35.6580', lng: '139.7016', notes: 'Book tickets in advance — rooftop observatory' },
  { id: 'p10', tripId: '1', dayId: 'd3', name: 'Tsukiji Outer Market', time: '07:00', category: 'Food', mapsUrl: 'https://maps.google.com/?q=Tsukiji+Outer+Market', lat: '35.6654', lng: '139.7707', notes: 'Best breakfast in Tokyo — fresh sushi and tamagoyaki' },
  { id: 'p11', tripId: '1', dayId: 'd3', name: 'TeamLab Planets', time: '14:00', category: 'Activity', mapsUrl: 'https://maps.google.com/?q=teamLab+Planets+Tokyo', lat: '35.6467', lng: '139.7845', notes: 'Pre-booked tickets essential. Wear shorts — you walk through water' },
  { id: 'p12', tripId: '1', dayId: 'd4', name: 'Tokyo Station', time: '09:15', category: 'Transport', mapsUrl: 'https://maps.google.com/?q=Tokyo+Station', lat: '35.6812', lng: '139.7671', notes: 'Nozomi 11 departs 09:33 — arrive early to find platform' },
  { id: 'p13', tripId: '1', dayId: 'd4', name: 'Kyoto Station', time: '12:10', category: 'Transport', mapsUrl: 'https://maps.google.com/?q=Kyoto+Station', lat: '34.9858', lng: '135.7588', notes: 'Arrive 12:10 · taxi or subway to hotel' },
  { id: 'p14', tripId: '1', dayId: 'd4', name: 'Nishiki Market', time: '14:00', category: 'Food', mapsUrl: 'https://maps.google.com/?q=Nishiki+Market+Kyoto', lat: '35.0050', lng: '135.7653', notes: '"Kyoto\'s Kitchen" — try pickles, tofu, skewers' },
  { id: 'p15', tripId: '1', dayId: 'd4', name: 'Gion District', time: '18:00', category: 'Sights', mapsUrl: 'https://maps.google.com/?q=Gion+District+Kyoto', lat: '35.0037', lng: '135.7752', notes: 'Evening stroll — best chance to spot a geisha on Hanamikoji St' },
];

export const DEMO_TRIPS = [
  {
    id: '1',
    name: 'Japan — Tokyo & Kyoto',
    emoji: '🇯🇵',
    status: 'upcoming',
    destinations: 'Tokyo, Kyoto, Osaka',
    startDate: '2025-06-12',
    endDate: '2025-06-26',
    budget: '£3,200',
    notes: 'JR Pass booked. Visa not required for UK passport.',
  },
  {
    id: '2',
    name: 'Lisbon & Porto',
    emoji: '🇵🇹',
    status: 'done',
    destinations: 'Lisbon, Porto',
    startDate: '2024-09-14',
    endDate: '2024-09-21',
    budget: '£1,100',
    notes: 'Amazing trip. Would go back to Porto in a heartbeat.',
  },
  {
    id: '3',
    name: 'Mexico City',
    emoji: '🇲🇽',
    status: 'dream',
    destinations: 'Mexico City, Oaxaca',
    startDate: '',
    endDate: '',
    budget: '',
    notes: 'Want to go in November for Día de los Muertos.',
  },
];

export const DEMO_DAYS = [
  {
    id: 'd1',
    tripId: '1',
    dayNumber: '1',
    date: '2025-06-12',
    title: 'Arrival — Shinjuku',
    location: 'Tokyo',
    morning: '10:30 Depart LHR on BA178',
    afternoon: 'Arrive NRT 06:45+1 · Narita Express to Shinjuku · Check in Ace Hotel',
    evening: 'Easy first night — Omoide Yokocho ramen alley',
    transport: 'Narita Express (¥3,070)',
    notes: 'Buy IC card at airport. Hotel check-in from 15:00.',
  },
  {
    id: 'd2',
    tripId: '1',
    dayNumber: '2',
    date: '2025-06-13',
    title: 'Harajuku & Shibuya',
    location: 'Tokyo',
    morning: '09:00 Meiji Shrine · 10:30 Harajuku Takeshita Street',
    afternoon: '13:00 Lunch at Afuri Ramen · 15:00 Shibuya Scramble & surrounding area',
    evening: '19:30 Dinner at Ichiran (solo booths) · Shibuya Sky observation deck',
    transport: 'Yamanote Line — day pass recommended',
    notes: 'Book Shibuya Sky in advance online.',
  },
  {
    id: 'd3',
    tripId: '1',
    dayNumber: '3',
    date: '2025-06-14',
    title: 'Tsukiji, Ginza & teamLab',
    location: 'Tokyo',
    morning: '07:00 Tsukiji Outer Market breakfast · Sushi at Sushi Dai',
    afternoon: '11:00 Ginza window shopping · TeamLab Planets 14:00 (pre-booked)',
    evening: '19:00 Dinner at DEN (Michelin star — reservation made)',
    transport: 'Subway day pass',
    notes: 'TeamLab tickets: ¥3,200 each. Smart casual for DEN.',
  },
  {
    id: 'd4',
    tripId: '1',
    dayNumber: '7',
    date: '2025-06-18',
    title: 'Shinkansen to Kyoto',
    location: 'Tokyo → Kyoto',
    morning: '09:33 Nozomi 11 from Tokyo Station · Arrive Kyoto 12:10',
    afternoon: 'Check in The Screen Kyoto · Nishiki Market walk',
    evening: 'Gion evening stroll · Dinner at Kikunoi (book ahead)',
    transport: 'Shinkansen — covered by JR Pass. Seat: Car 7, 12D',
    notes: 'Reserve shinkansen seats in advance even with JR Pass.',
  },
];

export const DEMO_DOCS = [
  {
    id: 'doc1',
    tripId: '1',
    name: 'BA178 — London to Tokyo',
    type: 'Flight',
    date: '2025-06-12',
    time: '10:30',
    ref: 'XY7GH2',
    fromTo: 'LHR → NRT',
    operator: 'British Airways',
    details: 'Seat 34A · 1 checked bag · Economy',
    cost: '£680',
    status: 'Confirmed',
  },
  {
    id: 'doc2',
    tripId: '1',
    name: 'BA179 — Tokyo to London',
    type: 'Flight',
    date: '2025-06-26',
    time: '13:00',
    ref: 'XY7GH2',
    fromTo: 'NRT → LHR',
    operator: 'British Airways',
    details: 'Seat 34A · 1 checked bag',
    cost: '',
    status: 'Confirmed',
  },
  {
    id: 'doc3',
    tripId: '1',
    name: 'Nozomi 11 — Tokyo to Kyoto',
    type: 'Train',
    date: '2025-06-18',
    time: '09:33',
    ref: 'JR-PASS-9921',
    fromTo: 'Tokyo → Kyoto',
    operator: 'JR Central',
    details: 'Car 7, Seat 12D · Covered by JR Pass',
    cost: '£0',
    status: 'Reserved',
  },
  {
    id: 'doc4',
    tripId: '1',
    name: 'JR Pass — 14 day',
    type: 'Pass',
    date: '2025-06-12',
    time: '',
    ref: 'JRP-4421-BB',
    fromTo: 'Valid Japan-wide',
    operator: 'JR Group',
    details: '14-day unlimited shinkansen + JR trains',
    cost: '£420',
    status: 'Confirmed',
  },
];

export const DEMO_STAYS = [
  {
    id: 's1',
    tripId: '1',
    name: 'Ace Hotel Tokyo',
    type: 'Hotel',
    checkIn: '2025-06-12',
    checkOut: '2025-06-18',
    address: '6-chome-5-3 Minamiaoyama, Minato City, Tokyo',
    mapsUrl: 'https://maps.google.com',
    ref: 'ACE-449012',
    cost: '£860',
    paid: 'Yes',
    checkInNotes: 'Self check-in from 15:00. Key at front desk.',
    extras: 'Wifi: AceGuest_12 · Breakfast not included',
  },
  {
    id: 's2',
    tripId: '1',
    name: 'The Screen Kyoto',
    type: 'Hotel',
    checkIn: '2025-06-18',
    checkOut: '2025-06-24',
    address: '640-1 Shimogoryomae-cho, Nakagyo-ku, Kyoto',
    mapsUrl: 'https://maps.google.com',
    ref: 'SCR-8821',
    cost: '£1,020',
    paid: 'No',
    checkInNotes: 'Check-in from 15:00. Pay on arrival.',
    extras: 'Wifi included · Near Nijo Castle',
  },
];
