export const DEMO_TRIPS = [
  {
    id: '1',
    name: 'Japan — Tokyo & Kyoto',
    emoji: '🇯🇵',
    status: 'upcoming',
    destinations: 'Tokyo, Kyoto, Osaka',
    startDate: '2025-06-12',
    endDate: '2025-06-26',
    budget: '£3,200',
    notes: 'JR Pass booked. Visa not required for UK passport.',
  },
  {
    id: '2',
    name: 'Lisbon & Porto',
    emoji: '🇵🇹',
    status: 'done',
    destinations: 'Lisbon, Porto',
    startDate: '2024-09-14',
    endDate: '2024-09-21',
    budget: '£1,100',
    notes: 'Amazing trip. Would go back to Porto in a heartbeat.',
  },
  {
    id: '3',
    name: 'Mexico City',
    emoji: '🇲🇽',
    status: 'dream',
    destinations: 'Mexico City, Oaxaca',
    startDate: '',
    endDate: '',
    budget: '',
    notes: 'Want to go in November for Día de los Muertos.',
  },
];

export const DEMO_DAYS = [
  {
    id: 'd1',
    tripId: '1',
    dayNumber: '1',
    date: '2025-06-12',
    title: 'Arrival — Shinjuku',
    location: 'Tokyo',
    morning: '10:30 Depart LHR on BA178',
    afternoon: 'Arrive NRT 06:45+1 · Narita Express to Shinjuku · Check in Ace Hotel',
    evening: 'Easy first night — Omoide Yokocho ramen alley',
    transport: 'Narita Express (¥3,070)',
    notes: 'Buy IC card at airport. Hotel check-in from 15:00.',
  },
  {
    id: 'd2',
    tripId: '1',
    dayNumber: '2',
    date: '2025-06-13',
    title: 'Harajuku & Shibuya',
    location: 'Tokyo',
    morning: '09:00 Meiji Shrine · 10:30 Harajuku Takeshita Street',
    afternoon: '13:00 Lunch at Afuri Ramen · 15:00 Shibuya Scramble & surrounding area',
    evening: '19:30 Dinner at Ichiran (solo booths) · Shibuya Sky observation deck',
    transport: 'Yamanote Line — day pass recommended',
    notes: 'Book Shibuya Sky in advance online.',
  },
  {
    id: 'd3',
    tripId: '1',
    dayNumber: '3',
    date: '2025-06-14',
    title: 'Tsukiji, Ginza & teamLab',
    location: 'Tokyo',
    morning: '07:00 Tsukiji Outer Market breakfast · Sushi at Sushi Dai',
    afternoon: '11:00 Ginza window shopping · TeamLab Planets 14:00 (pre-booked)',
    evening: '19:00 Dinner at DEN (Michelin star — reservation made)',
    transport: 'Subway day pass',
    notes: 'TeamLab tickets: ¥3,200 each. Smart casual for DEN.',
  },
  {
    id: 'd4',
    tripId: '1',
    dayNumber: '7',
    date: '2025-06-18',
    title: 'Shinkansen to Kyoto',
    location: 'Tokyo → Kyoto',
    morning: '09:33 Nozomi 11 from Tokyo Station · Arrive Kyoto 12:10',
    afternoon: 'Check in The Screen Kyoto · Nishiki Market walk',
    evening: 'Gion evening stroll · Dinner at Kikunoi (book ahead)',
    transport: 'Shinkansen — covered by JR Pass. Seat: Car 7, 12D',
    notes: 'Reserve shinkansen seats in advance even with JR Pass.',
  },
];

export const DEMO_DOCS = [
  {
    id: 'doc1',
    tripId: '1',
    name: 'BA178 — London to Tokyo',
    type: 'Flight',
    date: '2025-06-12',
    time: '10:30',
    ref: 'XY7GH2',
    fromTo: 'LHR → NRT',
    operator: 'British Airways',
    details: 'Seat 34A · 1 checked bag · Economy',
    cost: '£680',
    status: 'Confirmed',
  },
  {
    id: 'doc2',
    tripId: '1',
    name: 'BA179 — Tokyo to London',
    type: 'Flight',
    date: '2025-06-26',
    time: '13:00',
    ref: 'XY7GH2',
    fromTo: 'NRT → LHR',
    operator: 'British Airways',
    details: 'Seat 34A · 1 checked bag',
    cost: '',
    status: 'Confirmed',
  },
  {
    id: 'doc3',
    tripId: '1',
    name: 'Nozomi 11 — Tokyo to Kyoto',
    type: 'Train',
    date: '2025-06-18',
    time: '09:33',
    ref: 'JR-PASS-9921',
    fromTo: 'Tokyo → Kyoto',
    operator: 'JR Central',
    details: 'Car 7, Seat 12D · Covered by JR Pass',
    cost: '£0',
    status: 'Reserved',
  },
  {
    id: 'doc4',
    tripId: '1',
    name: 'JR Pass — 14 day',
    type: 'Pass',
    date: '2025-06-12',
    time: '',
    ref: 'JRP-4421-BB',
    fromTo: 'Valid Japan-wide',
    operator: 'JR Group',
    details: '14-day unlimited shinkansen + JR trains',
    cost: '£420',
    status: 'Confirmed',
  },
];

export const DEMO_STAYS = [
  {
    id: 's1',
    tripId: '1',
    name: 'Ace Hotel Tokyo',
    type: 'Hotel',
    checkIn: '2025-06-12',
    checkOut: '2025-06-18',
    address: '6-chome-5-3 Minamiaoyama, Minato City, Tokyo',
    mapsUrl: 'https://maps.google.com',
    ref: 'ACE-449012',
    cost: '£860',
    paid: 'Yes',
    checkInNotes: 'Self check-in from 15:00. Key at front desk.',
    extras: 'Wifi: AceGuest_12 · Breakfast not included',
  },
  {
    id: 's2',
    tripId: '1',
    name: 'The Screen Kyoto',
    type: 'Hotel',
    checkIn: '2025-06-18',
    checkOut: '2025-06-24',
    address: '640-1 Shimogoryomae-cho, Nakagyo-ku, Kyoto',
    mapsUrl: 'https://maps.google.com',
    ref: 'SCR-8821',
    cost: '£1,020',
    paid: 'No',
    checkInNotes: 'Check-in from 15:00. Pay on arrival.',
    extras: 'Wifi included · Near Nijo Castle',
  },
];
